/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
static yyconst short int yy_accept[279] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       98,   96,    9,   35,   96,   50,   20,   96,   41,   42,
       17,   15,   48,   16,   18,   94,   47,   49,   39,   21,
       37,   93,   93,   93,   93,   45,   46,   96,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   43,   96,   44,    4,    2,
        1,    4,    5,    7,   97,   11,   13,   97,   96,   96,
       96,   36,    0,   89,    0,   50,   26,   29,    0,   51,
        0,   51,   19,   24,   22,   23,    0,   25,    0,   94,
        0,   40,   34,   38,    0,   93,   93,   93,   93,    0,

       51,    0,   31,   93,   74,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   55,   93,   63,
       67,   93,   93,   93,   85,   93,   93,   93,   93,   93,
       93,   93,   30,    1,    0,    5,    7,    0,   11,   13,
        0,   89,    0,    0,    0,   89,    0,   90,    0,   92,
        0,    0,    0,   28,   27,   95,   33,   32,   93,   93,
       93,    0,   91,    0,    0,   69,   93,   93,   93,   93,
       93,   93,   93,   75,   80,   93,   93,   93,   93,   71,
       93,   93,   93,   93,   93,   93,   82,   93,   93,   93,
       73,   93,   93,   93,    3,    8,    6,    6,   14,   12,

       12,   10,   10,   10,    0,    0,    0,    0,   93,   60,
       53,    0,    0,   93,   93,   93,   93,   88,   93,   93,
       57,   56,   93,   93,   76,   93,   93,   93,   93,   93,
       59,   93,   93,   93,   83,   93,    0,    0,    0,   95,
       52,    0,    0,   93,   84,   54,   61,   65,   93,    0,
       93,   93,   93,   93,   93,   87,   93,   64,   93,   78,
       86,   79,   93,    0,   62,   93,   81,   58,   72,   93,
       68,   93,   57,   66,   93,   70,   77,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   26,
       24,   24,   24,   24,   24,   24,   24,   27,   24,   24,
       24,   24,   24,   28,   24,   24,   24,   24,   24,   24,
       29,   30,   31,   32,   24,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   24,   42,   43,   44,   45,
       46,   47,   24,   48,   49,   50,   51,   24,   52,   53,
       54,   24,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    3,    4,
        4,    1,    1,    5,    1,    1,    1,    6,    1,    1,
        1,    1,    1,    6,    6,    6,    6,    6,    7,    3,
        7,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    3,    1
    } ;

static yyconst short int yy_base[294] =
    {   0,
        0,    0,   56,   61,   62,   63,   64,   69,   70,   71,
      461,  462,  462,  438,   55,    0,  437,  436,   40,  435,
       65,  434,  433,  432,   64,   66,  431,  430,   69,  429,
       73,    0,  417,  403,  400,   61,  425,  424,   52,  397,
       65,  407,   60,   59,  400,   84,  409,  408,  394,  391,
      405,   69,  389,   74,  395,  413,  412,  411,  462,  462,
      429,  125,    0,  126,  401,    0,  127,  400,  132,  133,
      134,  462,  116,  462,  118,    0,  462,  462,  136,  138,
      143,  462,  407,  462,  462,  462,  406,  462,  409,  135,
      404,  462,  462,  462,  403,    0,  381,  378,  371,  130,

      144,  145,  462,  385,   91,  387,  382,  369,  384,  371,
      117,   75,  380,  369,  365,  366,  365,    0,  363,    0,
        0,  365,  358,  118,    0,  358,  365,  355,  350,  362,
      352,  364,  462,  397,  160,    0,  161,  369,    0,  162,
      368,  168,  169,  175,  167,  462,  367,  462,  394,  462,
      346,  184,  189,  462,  462,  183,  462,  462,  345,  356,
      355,  342,  462,  188,  190,    0,  353,  344,  347,  354,
      349,  336,  334,    0,    0,  345,  345,  344,  347,    0,
      335,  344,  331,  342,  340,  331,    0,  324,  323,  320,
        0,  327,  329,  325,  462,  462,  462,  322,  462,  462,

      320,  462,  462,  181,  356,  195,  196,  214,  320,    0,
        0,  191,  199,  300,  306,  278,  279,    0,  268,  269,
        0,  306,  253,  225,    0,  234,  218,  229,  224,  217,
        0,  225,  212,  222,    0,  222,  201,  212,  239,  238,
        0,  220,  221,  205,    0,    0,    0,    0,  209,  212,
      199,  204,  203,  193,  209,    0,  206,    0,  191,    0,
        0,    0,  177,  176,    0,  142,    0,    0,    0,  158,
        0,  127,  462,    0,   66,    0,    0,  462,  270,  277,
      284,  291,  298,  305,   82,  312,  318,  325,  332,  339,
      346,  353,  360

    } ;

static yyconst short int yy_def[294] =
    {   0,
      278,    1,  279,  279,  280,  280,  281,  281,    1,    1,
      278,  278,  278,  278,  282,  283,  278,  278,  284,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  285,  285,  285,  285,  286,  278,  278,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  278,  278,  278,  278,  278,
      278,  278,  287,  278,  278,  288,  278,  278,  282,  278,
      278,  278,  289,  278,  278,  283,  278,  278,  284,  284,
      284,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  285,  285,  285,  285,  286,

      286,  286,  278,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  278,  278,  278,  287,  278,  290,  288,  278,
      291,  278,  289,  278,  289,  278,  278,  278,  282,  278,
      292,  284,  284,  278,  278,  278,  278,  278,  285,  285,
      285,  293,  278,  286,  286,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  289,  289,  292,  292,  278,  285,  285,
      285,  293,  293,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  292,  292,  278,  278,
      285,  293,  293,  285,  285,  285,  285,  285,  285,  278,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  278,  285,  285,  285,  285,  285,  285,
      285,  285,  278,  285,  285,  285,  285,    0,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278

    } ;

static yyconst short int yy_nxt[520] =
    {   0,
       12,   13,   12,   14,   15,   16,   17,   18,   12,   19,
       20,   21,   22,   23,   24,   12,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   34,   35,   36,   12,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   32,
       46,   32,   47,   48,   49,   50,   51,   52,   32,   53,
       32,   54,   32,   55,   56,   57,   58,   60,   61,   74,
       62,   80,   60,   61,   62,   62,   64,   64,   67,   62,
       64,   64,   67,   67,   69,   69,   83,   67,   70,   70,
       87,   89,  101,   90,   75,   88,   84,   96,   81,   91,
       92,   65,   65,   68,   94,   95,  104,  108,   68,  114,

      105,  127,  112,  106,  115,  128,  116,  109,  277,  102,
      110,   62,  113,  130,  131,  176,   62,   64,   64,   67,
      146,  118,  148,  177,   67,   71,   71,  119,  120,  135,
      137,  140,  121,  135,  137,  140,  142,  144,  144,  167,
      143,  144,  144,  162,  168,  147,  150,  149,  150,  151,
       89,  151,   90,  150,  174,  133,  151,  162,  162,  175,
      163,   75,  186,  276,  195,  196,  199,  187,  195,  196,
      199,   74,  202,  203,  163,  163,  202,  204,  164,  202,
      135,  137,  140,  202,  152,   74,  152,  143,  144,  144,
      275,  153,  164,  165,  150,  274,  147,  151,  147,  150,

      156,  162,  151,  162,  162,  150,  150,  208,  151,  151,
      147,  150,  162,  273,  151,  195,  196,  199,  163,  208,
      163,  163,  150,  202,  204,  151,  239,  272,  239,  163,
      202,  240,  152,  162,  162,  271,  164,  153,  165,  242,
      270,  269,  268,  237,  238,  267,  266,  243,  265,  237,
      163,  163,  264,  263,  262,  240,  240,  261,  260,  259,
      238,  258,  257,  256,  255,  254,  253,  252,  242,  243,
       59,   59,   59,   59,   59,   59,   59,   63,   63,   63,
       63,   63,   63,   63,   66,   66,   66,   66,   66,   66,
       66,   73,   73,   73,   73,   73,   73,   73,   76,  251,

       76,   76,   76,   76,   76,   79,   79,   79,  250,  249,
       79,   79,  100,  100,  100,  100,  248,  100,  136,  136,
      247,  136,  136,  136,  136,  139,  139,  246,  139,  139,
      139,  139,  145,  145,  145,  145,  145,  145,  145,  197,
      245,  197,  197,  197,  197,  197,  200,  244,  200,  200,
      200,  200,  200,  206,  206,  206,  241,  278,  206,  206,
      212,  212,  212,  212,  200,  212,  197,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  211,  210,  209,  207,  278,  205,  201,  198,  134,

      194,  193,  192,  191,  190,  189,  188,  185,  184,  183,
      182,  181,  180,  179,  178,  173,  172,  171,  170,  169,
      166,  161,  160,  159,  158,  157,  156,  155,  154,  141,
      138,  134,   82,  133,   82,  132,  129,  126,  125,  124,
      123,  122,  117,  111,  107,  103,   82,   99,   98,   97,
       93,   82,   82,   86,   82,   85,   82,   78,   77,   72,
      278,   11,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yyconst short int yy_chk[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,   15,
        3,   19,    4,    4,    3,    4,    5,    6,    7,    4,
        5,    6,    7,    8,    9,   10,   21,    8,    9,   10,
       25,   26,   36,   26,   15,   25,   21,  285,   19,   29,
       29,    5,    6,    7,   31,   31,   39,   41,    8,   44,

       39,   52,   43,   39,   44,   52,   44,   41,  275,   36,
       41,    3,   43,   54,   54,  112,    4,    5,    6,    7,
       73,   46,   75,  112,    8,    9,   10,   46,   46,   62,
       64,   67,   46,   62,   64,   67,   69,   70,   71,  105,
       69,   70,   71,  100,  105,   73,   79,   75,   80,   79,
       90,   80,   90,   81,  111,   71,   81,  101,  102,  111,
      100,   69,  124,  272,  135,  137,  140,  124,  135,  137,
      140,  145,  142,  143,  101,  102,  142,  143,  100,  144,
       62,   64,   67,  144,   79,  204,   80,   69,   70,   71,
      270,   81,  101,  102,  152,  266,  145,  152,  143,  153,

      156,  164,  153,  165,  212,  206,  207,  156,  206,  207,
      204,  237,  213,  264,  237,  135,  137,  140,  164,  156,
      165,  212,  238,  142,  143,  238,  208,  263,  208,  213,
      144,  208,  152,  242,  243,  259,  164,  153,  165,  212,
      257,  255,  254,  206,  207,  253,  252,  213,  251,  237,
      242,  243,  250,  249,  244,  240,  239,  236,  234,  233,
      238,  232,  230,  229,  228,  227,  226,  224,  242,  243,
      279,  279,  279,  279,  279,  279,  279,  280,  280,  280,
      280,  280,  280,  280,  281,  281,  281,  281,  281,  281,
      281,  282,  282,  282,  282,  282,  282,  282,  283,  223,

      283,  283,  283,  283,  283,  284,  284,  284,  222,  220,
      284,  284,  286,  286,  286,  286,  219,  286,  287,  287,
      217,  287,  287,  287,  287,  288,  288,  216,  288,  288,
      288,  288,  289,  289,  289,  289,  289,  289,  289,  290,
      215,  290,  290,  290,  290,  290,  291,  214,  291,  291,
      291,  291,  291,  292,  292,  292,  209,  205,  292,  292,
      293,  293,  293,  293,  201,  293,  198,  194,  193,  192,
      190,  189,  188,  186,  185,  184,  183,  182,  181,  179,
      178,  177,  176,  173,  172,  171,  170,  169,  168,  167,
      162,  161,  160,  159,  151,  149,  147,  141,  138,  134,

      132,  131,  130,  129,  128,  127,  126,  123,  122,  119,
      117,  116,  115,  114,  113,  110,  109,  108,  107,  106,
      104,   99,   98,   97,   95,   91,   89,   87,   83,   68,
       65,   61,   58,   57,   56,   55,   53,   51,   50,   49,
       48,   47,   45,   42,   40,   38,   37,   35,   34,   33,
       30,   28,   27,   24,   23,   22,   20,   18,   17,   14,
       11,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include "parser.tab.h"
/* Regular expressions to match tokens */
/*WHITESPACE              [ \t]*/
/* Define a stack to store indentation levels */
#line 95 "lexer.l"
typedef struct stack {
    int data;
    struct stack *next;
} stack;

stack *top = NULL;

/* Push a value to the stack */
void push(int value) {
    stack *new_node = (stack *) malloc(sizeof(stack));
    new_node->data = value;
    new_node->next = top;
    top = new_node;
}

/* Pop a value from the stack */
int pop() {
    if (top == NULL) 
        return -1;
    int value = top->data;
    stack *temp = top;
    top = top->next;
    free(temp);
    return value;
}

/* Peek the top value of the stack */
int peek() {
    if (top == NULL) 
        return -1;
    return top->data;
}

/* Count the number of spaces at the beginning of a string */
int count_spaces(char *str) {
    int count = 0;
    while (*str == ' ' || *str == '\t') {    
        count++;
        str++;
    }
    return count;
}

/* Handle indentation and dedentation */
int handle_indent(char *str) {
    int new_indent = count_spaces(str);
    int current_indent = peek();
    if (new_indent > current_indent) {
        push(new_indent);
        return new_indent;
    } else if (new_indent < current_indent) {
        while (new_indent < current_indent) {
            int value = pop();
            current_indent = peek();
            return value;
        }
        if (new_indent == current_indent) 
            return 0;
        else {
            fprintf(stderr, "Invalid indentation\n");
            exit(1);
        }
    } else 
        return 0;
}
/* start state for parsing the indentation */
#define indent 1
 
#define comment 2

#define string 3

/* normal start state for everything else */
#define normal 4
 
#line 659 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 169 "lexer.l"


    // %{
    //     BEGIN indent;
    // %}

#line 817 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 462 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 175 "lexer.l"
{ 
    int current = count_spaces(yytext);
    int token = handle_indent(yytext); 
    if (token != 0) { 
        if(current < token){
            /*printf("DEDENT: %d \n", token); */
            return DEDENT;
        }
        else{
            /*printf("INDENT: %d\n", token);*/
            return INDENT;
        }
        BEGIN indent;
    }
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 191 "lexer.l"
{ 
    // printf("\n");
    BEGIN indent;
    return NEWLINE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 197 "lexer.l"
{ 
    BEGIN comment;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 201 "lexer.l"
{
    unput(*yytext);
    BEGIN normal;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 206 "lexer.l"
{ /*printf("inside triple comment1: %s \n", yytext);*/ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 207 "lexer.l"
{ /*printf("inside triple comment2: %s \n", yytext);*/ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 208 "lexer.l"
{ /*printf("inside triple comment3: %s \n", yytext);*/ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 209 "lexer.l"
{ /*printf("end of triple comment: %s \n", yytext);*/ BEGIN (indent); return MULTILINECOMMENT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 211 "lexer.l"
{
    // printf("hkljhkljkljhkhkljhkhkhlk\n"); 
    BEGIN indent;
    return NEWLINE;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 217 "lexer.l"
{
    BEGIN string;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 221 "lexer.l"
{ /*printf("inside triple string: %s \n", yytext);*/ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 222 "lexer.l"
{ /*printf("inside triple string: %s \n", yytext);*/ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 223 "lexer.l"
{ /*printf("inside triple string: %s \n", yytext);*/ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 224 "lexer.l"
{ /*printf("end of triple string: %s \n", yytext);*/ BEGIN (indent); return MULTILINESTRING; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 226 "lexer.l"
{/*printf("ADD: %s\n", yytext);*/return ADD;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 227 "lexer.l"
{/*printf("MINUS: %s\n", yytext);*/return MINUS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 228 "lexer.l"
{/*printf("MULTIPLY: %s\n", yytext);*/return MULTIPLY;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 229 "lexer.l"
{/*printf("DIVIDE: %s\n", yytext);*/return DIVIDE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 230 "lexer.l"
{/*printf("POWER: %s\n", yytext);*/return POWER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 231 "lexer.l"
{/*printf("MODULO: %s\n", yytext);*/return MODULO;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 232 "lexer.l"
{/*printf("ASSIGN: %s\n", yytext);*/return ASSIGN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 233 "lexer.l"
{/*printf("ASSIGN_ADD: %s\n", yytext);*/return ASSIGNADD;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "lexer.l"
{/*printf("ASSIGN_MINUS: %s\n", yytext);*/return ASSIGNMINUS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 235 "lexer.l"
{/*printf("ASSIGN_MULTIPLY: %s\n", yytext);*/return ASSIGNMULTIPLY;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "lexer.l"
{/*printf("ASSIGN_DIVIDE: %s\n", yytext);*/return ASSIGNDIVIDE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 237 "lexer.l"
{/*printf("ASSIGN_MODULO: %s\n", yytext);*/return ASSIGNMODULO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "lexer.l"
{/*printf("ASSIGN_FLOOR_DIVISION: %s\n", yytext);*/return ASSIGNFLOORDIVISION;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "lexer.l"
{/*printf("ASSIGN_EXPONINTIATION: %s\n", yytext);*/return ASSIGNEXPONINTIATION;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 240 "lexer.l"
{/*printf("ASSIGN_BITWISE_AND: %s\n", yytext);*/return ASSIGNBITWISEAND;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 241 "lexer.l"
{/*printf("ASSIGN_BITWISE_OR: %s\n", yytext);*/return ASSIGNBITWISEOR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 242 "lexer.l"
{/*printf("ASSIGN_BITWISE_XOR: %s\n", yytext);*/return ASSIGNBITWISEXOR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 243 "lexer.l"
{/*printf("ASSIGN_RIGHT_SHIFT: %s\n", yytext);*/return ASSIGNRIGHTSHIFT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 244 "lexer.l"
{/*printf("ASSIGN_LEFT_SHIFT: %s\n", yytext);*/return ASSIGNLEFTSHIFT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 245 "lexer.l"
{/*printf("EQUAL: %s\n", yytext);*/return EQUAL;}    
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 246 "lexer.l"
{/*printf("NOT: %s\n", yytext);*/return NOT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "lexer.l"
{/*printf("NOT_EQUAL: %s\n", yytext);*/return NOTEQUAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "lexer.l"
{/*printf("GREATER_THAN: %s\n", yytext);*/return GREATERTHAN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 249 "lexer.l"
{/*printf("GREATER_OR_EQUAL: %s\n", yytext);*/return GREATEROREQUAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 250 "lexer.l"
{/*printf("LESS_THAN: %s\n", yytext);*/return LESSTHAN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 251 "lexer.l"
{/*printf("LESS_OR_EQUAL: %s\n", yytext);*/return LESSOREQUAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 252 "lexer.l"
{/*printf("LEFT_PARENTHES: %s\n", yytext);*/return LEFT_PARENTHES;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 253 "lexer.l"
{/*printf("RIGHT_PARENTHES: %s\n", yytext);*/return RIGHT_PARENTHES;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 254 "lexer.l"
{/*printf("LEFT_BRACES: %s\n", yytext);*/return LEFT_BRACES;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 255 "lexer.l"
{/*printf("RIGHT_BRACES: %s\n", yytext);*/return RIGHT_BRACES;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 256 "lexer.l"
{/*printf("LEFT_BRACKETS: %s\n", yytext);*/return LEFT_BRACKETS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 257 "lexer.l"
{/*printf("RIGHT_BRACKETS: %s\n", yytext);*/return RIGHT_BRACKETS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 258 "lexer.l"
{/*printf("COLON: %s\n", yytext);*/return COLON;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 259 "lexer.l"
{/*printf("COMMA: %s\n", yytext);*/return COMMA;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 260 "lexer.l"
{/*printf("SEMICOLON: %s\n", yytext);*/return SEMICOLON;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 261 "lexer.l"
{/*printf("COMMENT: %s\n", yytext);*/return COMMENT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 262 "lexer.l"
{/*printf("OPERATOR: %s\n", yytext);*/return OPERATORS;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 263 "lexer.l"
{/*printf("KEYWORD_FALSE: %s \n",yytext);*/return KEYWORD_FALSE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 264 "lexer.l"
{/*printf("KEYWORD_TRUE: %s \n",yytext);*/return KEYWORD_TRUE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 265 "lexer.l"
{/*printf("KEYWORD_AWAIT: %s \n",yytext);*/return KEYWORD_AWAIT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 266 "lexer.l"
{/*printf("KEYWORD_IF: %s \n",yytext);*/return KEYWORD_IF;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 267 "lexer.l"
{/*printf("KEYWORD_ELSE: %s \n",yytext);*/return KEYWORD_ELSE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 268 "lexer.l"
{/*printf("KEYWORD_ELSE_IF: %s \n",yytext);*/return KEYWORD_ELSE_IF;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 269 "lexer.l"
{/*printf("KEYWORD_IMPORT: %s \n",yytext);*/return KEYWORD_IMPORT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 270 "lexer.l"
{/*printf("KEYWORD_PASS: %s \n",yytext);*/return KEYWORD_PASS;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 271 "lexer.l"
{/*printf("NONE: %s \n",yytext);*/return KEYWORD_NONE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 272 "lexer.l"
{/*printf("BREAK: %s \n",yytext);*/return KEYWORD_BREAK;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 273 "lexer.l"
{/*printf("KEYWORD_PASS: %s \n",yytext);*/return KEYWORD_EXCEPT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 274 "lexer.l"
{/*printf("KEYWORD_IN: %s \n",yytext);*/return KEYWORD_IN;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 275 "lexer.l"
{/*printf("KEYWORD_RAISE: %s \n",yytext);*/return KEYWORD_RAISE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 276 "lexer.l"
{/*printf("KEYWORD_CLASS: %s \n",yytext);*/return KEYWORD_CLASS;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 277 "lexer.l"
{/*printf("KEYWORD_FINALLY: %s \n",yytext);*/return KEYWORD_FINALLY;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 278 "lexer.l"
{/*printf("KEYWORD_IS: %s \n",yytext);*/return KEYWORD_IS;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 279 "lexer.l"
{/*printf("KEYWORD_RETURN: %s \n",yytext);*/return KEYWORD_RETURN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 280 "lexer.l"
{/*printf("KEYWORD_AND: %s \n",yytext);*/return KEYWORD_AND;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 281 "lexer.l"
{/*printf("KEYWORD_CONTINUE: %s \n",yytext);*/return KEYWORD_CONTINUE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 282 "lexer.l"
{/*printf("KEYWORD_FOR: %s \n",yytext);*/return KEYWORD_FOR;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 283 "lexer.l"
{/*printf("KEYWORD_LAMBDA: %s \n",yytext);*/return KEYWORD_LAMBDA;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 284 "lexer.l"
{/*printf("KEYWORD_TRY: %s \n",yytext);*/return KEYWORD_TRY;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 285 "lexer.l"
{/*printf("KEYWORD_AS: %s \n",yytext);*/return KEYWORD_AS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 286 "lexer.l"
{/*printf("KEYWORD_DEF: %s \n",yytext);*/return KEYWORD_DEF;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 287 "lexer.l"
{/*printf("KEYWORD_FROM: %s \n",yytext);*/return KEYWORD_FROM;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 288 "lexer.l"
{/*printf("KEYWORD_NONLOCAL: %s \n",yytext);*/return KEYWORD_NONLOCAL;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 289 "lexer.l"
{/*printf("KEYWORD_WHILE: %s \n",yytext);*/return KEYWORD_WHILE;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 290 "lexer.l"
{/*printf("KEYWORD_ASSERT: %s \n",yytext);*/return KEYWORD_ASSERT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 291 "lexer.l"
{/*printf("KEYWORD_DEL: %s \n",yytext);*/return KEYWORD_DEL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 292 "lexer.l"
{/*printf("KEYWORD_GLOBAL: %s \n",yytext);*/return KEYWORD_GLOBAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 293 "lexer.l"
{/*printf("KEYWORD_NOT: %s \n",yytext);*/return KEYWORD_NOT;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 294 "lexer.l"
{/*printf("KEYWORD_WITH: %s \n",yytext);*/return KEYWORD_WITH;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 295 "lexer.l"
{/*printf("KEYWORD_ASYNC: %s \n",yytext);*/return KEYWORD_ASYNC;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 296 "lexer.l"
{/*printf("KEYWORD_OR: %s \n",yytext);*/return KEYWORD_OR;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 297 "lexer.l"
{/*printf("KEYWORD_YIELD: %s \n",yytext);*/return KEYWORD_YIELD;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 298 "lexer.l"
{/*printf("KEYWORD_MATCH: %s \n",yytext);*/return KEYWORD_MATCH;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 299 "lexer.l"
{/*printf("KEYWORD_CASE: %s \n",yytext);*/return KEYWORD_CASE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 300 "lexer.l"
{/*printf("STRING_LITERAL: %s\n", yytext);*/return LITERALSTRING;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 301 "lexer.l"
{/*printf("CHAR_LITERAL: %s\n", yytext);*/return LITERALCHAR;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 302 "lexer.l"
{/*printf("list: %s \n",yytext);*/return LIST;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 303 "lexer.l"
{/*printf("tuple: %s \n",yytext);*/return TUPLE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 304 "lexer.l"
{/*printf("IDENTIFIER: %s \n",yytext);*/return IDENTIFIER;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 305 "lexer.l"
{/*printf("INTEGER: %s\n", yytext);*/return INTEGER;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 306 "lexer.l"
{/*printf("FLOAT: %s\n", yytext);*/return FLOAT;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 307 "lexer.l"
{/* Ignore everything else. */}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(indent):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(string):
case YY_STATE_EOF(normal):
#line 308 "lexer.l"
{
                            while (peek() != -1) 
                                //printf("DEDENT: %d\n", pop());
                                return DEDENT;
                        }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 314 "lexer.l"
ECHO;
	YY_BREAK
#line 1426 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 278);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 314 "lexer.l"
